stages:
  - build
  - test
  - code_quality

build:
  stage: build
  script:
    - gradle build -x test
  tags:
    - gradle

test:
  stage: test
  script:
    - gradle test
  tags:
    - gradle
  artifacts:
    untracked: true
    when: on_failure
    expire_in: 1 day

code_quality:
  stage: code_quality
  tags:
    - docker
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
        --env SOURCE_CODE="$PWD"
        --volume "$PWD":/code
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/security-products/codequality:$SP_VERSION" /code
  artifacts:
    reports:
      codequality: gl-code-quality-report.json