stages:
  - build
  - test
  - qa

build:
  stage: build
  script:
    - gradle build -x test
  tags:
    - gradle

test:
  stage: test
  script:
    - gradle test
  tags:
    - gradle
  artifacts:
    untracked: true
    when: on_failure
    expire_in: 1 week

mutation:
  stage: qa
  script:
    - gradle pitest
  tags:
    - gradle
  artifacts:
    untracked: true
    when: always
    expire_in: 1 week
  allow_failure: true

coverage:
  stage: qa
  script:
    - gradle jacocoTestReport
    - gradle codeCoverageInfo
  tags:
    - gradle
  artifacts:
    untracked: true
    when: always
    expire_in: 1 week
  allow_failure: true
  
checks:
  stage: qa
  script:
  - gradle check
  tags: gradle
  artifacts:
    untracked: true
    when: always
    expire_in: 1 week
  allow_failure: true
