stages:
  - build

build:
  stage: build
  script:
    - gradle build
  tags:
    - gradle
  artifacts:
    untracked: true
    paths:
      - temp/
    when: on_failure
    expire_in: 1 day