stages:
  - build
  - test
  - qa

build:
  stage: build
  script:
    - chmod +x ./gradlew
    - ./gradlew build -x test

test:
  stage: test
  script:
    - chmod +x ./gradlew
    - ./gradlew test
  artifacts:
    untracked: true
    when: on_failure
    expire_in: 1 week

mutation:
  stage: qa
  script:
    - chmod +x ./gradlew
    - ./gradlew pitest
  artifacts:
    untracked: true
    when: always
    expire_in: 1 week
  allow_failure: true

coverage:
  stage: qa
  script:
    - chmod +x ./gradlew
    - ./gradlew jacocoTestReport
    - ./gradlew codeCoverageInfo
  artifacts:
    untracked: true
    when: always
    expire_in: 1 week
  allow_failure: true
  
checks:
  stage: qa
  script:
  - chmod +x ./gradlew
  - ./gradlew check
  artifacts:
    untracked: true
    when: always
    expire_in: 1 week
  allow_failure: true
